'use client';

import { motion } from 'framer-motion';
import { Scale, CheckCircle, AlertTriangle, FileCheck } from 'lucide-react';

export default function TermsOfServicePage() {
  const sections = [
    { id: 'acceptance', title: '1. Acceptance of Terms' },
    { id: 'service-usage', title: '2. Use of Service' },
    { id: 'content-rights', title: '3. Content & Intellectual Property' },
    { id: 'ai-processing', title: '4. AI Processing Limitations' },
    { id: 'termination', title: '5. Termination' },
  ];

  return (
    <div className="min-h-screen bg-[#050505] text-white pt-32 pb-24 selection:bg-[#9945FF]/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row gap-12">
        {/* Sidebar */}
        <div className="w-full md:w-64 flex-shrink-0">
          <div className="sticky top-32">
            <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-4">Contents</h3>
            <nav className="flex flex-col space-y-2">
              {sections.map((section) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="text-gray-500 hover:text-[#9945FF] transition-colors duration-200 text-sm"
                >
                  {section.title}
                </a>
              ))}
            </nav>
            <div className="mt-8 p-4 bg-white/5 border border-white/10 rounded-lg backdrop-blur-md">
              <Scale className="w-6 h-6 text-[#9945FF] mb-2" />
              <p className="text-xs text-gray-400">
                Last updated: May 26, 2026<br />
                Effective date: June 1, 2026
              </p>
            </div>
          </div>
        </div>

        {/* Content */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex-1 max-w-4xl"
        >
          <div className="mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-6 tracking-tight">Terms of Service</h1>
            <p className="text-xl text-gray-400 leading-relaxed">
              These terms govern your use of the ClipFlow platform. By creating an account or using our AI clipping tools, you agree to these conditions.
            </p>
          </div>

          <div className="space-y-12 text-gray-300 leading-relaxed">
            <section id="acceptance" className="scroll-mt-32">
              <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
                <CheckCircle className="w-6 h-6 text-[#00E5FF]" />
                1. Acceptance of Terms
              </h2>
              <p className="mb-4">
                By accessing or using ClipFlow's web application, API, or integration services (collectively, the "Service"), you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service.
              </p>
            </section>

            <section id="service-usage" className="scroll-mt-32">
              <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
                <FileCheck className="w-6 h-6 text-[#00FFA3]" />
                2. Use of Service
              </h2>
              <p className="mb-4">
                You must provide accurate information when registering an account. You are responsible for safeguarding the password and for all activities under your account. 
                Our infrastructure is designed for high-performance video processing; intentional abuse or circumvention of rate limits will result in immediate termination.
              </p>
            </section>

            <section id="content-rights" className="scroll-mt-32">
              <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
                <Scale className="w-6 h-6 text-[#9945FF]" />
                3. Content & Intellectual Property
              </h2>
              <p className="mb-4">
                You retain all rights to the raw video content you upload and the clipped output generated by the Service. 
                ClipFlow claims no ownership over your intellectual property. However, you grant ClipFlow a limited, worldwide license to host, store, and process your content solely for the purpose of providing the Service.
              </p>
              <p className="text-gray-400 italic">
                You represent and warrant that you own or have the necessary licenses to process the content you upload, including clearance for any copyrighted audio or visual material.
              </p>
            </section>

            <section id="ai-processing" className="scroll-mt-32">
              <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
                <AlertTriangle className="w-6 h-6 text-yellow-500" />
                4. AI Processing Limitations
              </h2>
              <p className="mb-4">
                ClipFlow utilizes advanced machine learning models for transcription, facial tracking, and semantic understanding. While we strive for unicorn-level accuracy, AI is probabilistic. 
                We do not guarantee 100% accuracy in transcription, speaker diarization, or auto-framing. You are responsible for reviewing AI-generated clips before publication.
              </p>
            </section>

            <section id="termination" className="scroll-mt-32">
              <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
                <CheckCircle className="w-6 h-6 text-[#00E5FF]" />
                5. Termination
              </h2>
              <p className="mb-4">
                We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. 
                Upon termination, your right to use the Service will immediately cease and all data will be scheduled for secure deletion within 30 days.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
